# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170309_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='num_limit',
            new_name='Limit on Number of Results',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='price_limit',
            new_name='Limit on Price',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='city',
            new_name='Please Choose a City',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='best_worst',
            new_name='Specify Best or Worst',
        ),
    ]
